<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'SETTINGS_INDEX', 'SETTINGS_CREATE', 'SETTINGS_EDIT', 'SETTINGS_DELETE',
            'USER_INDEX', 'USER_CREATE', 'USER_EDIT', 'USER_DELETE',
            'ROLE_INDEX', 'ROLE_CREATE', 'ROLE_EDIT', 'ROLE_DELETE', 'ROLE_SHOW',
            'PERMISSION_INDEX',
            'PROFILE_SHOW', 'PROFILE_EDIT', 'PROFILE_DELETE',
            'BANNAR_INDEX', 'BANNAR_CREATE', 'BANNAR_EDIT', 'BANNAR_DELETE',
            'STATIC_BANNAR_INDEX', 'STATIC_BANNAR_CREATE', 'STATIC_BANNAR_EDIT', 'STATIC_BANNAR_DELETE',
            'BRAND_MARQUEE_INDEX', 'BRAND_MARQUEE_CREATE', 'BRAND_MARQUEE_EDIT', 'BRAND_MARQUEE_DELETE',
            'HOMEPAGE_SECTION_INDEX', 'HOMEPAGE_SECTION_CREATE', 'HOMEPAGE_SECTION_EDIT', 'HOMEPAGE_SECTION_DELETE',
            'CATEGORY_INDEX', 'CATEGORY_CREATE', 'CATEGORY_EDIT', 'CATEGORY_DELETE', 'CATEGORY_SHOW',
            'PRODUCT_INDEX', 'PRODUCT_CREATE', 'PRODUCT_EDIT', 'PRODUCT_DELETE', 'PRODUCT_SHOW',
            'SIZE_INDEX', 'SIZE_CREATE', 'SIZE_EDIT', 'SIZE_DELETE', 'SIZE_SHOW',
            'VARIANT_INDEX', 'VARIANT_CREATE', 'VARIANT_EDIT', 'VARIANT_DELETE', 'VARIANT_SHOW',
            'PRODUCT_STATUS_INDEX', 'PRODUCT_STATUS_CREATE', 'PRODUCT_STATUS_EDIT', 'PRODUCT_STATUS_DELETE', 'PRODUCT_STATUS_SHOW',
            'CONTACT_INDEX', 'CONTACT_CREATE', 'CONTACT_EDIT', 'CONTACT_DELETE',
            'FOOTER_INDEX', 'FOOTER_CREATE', 'FOOTER_EDIT', 'FOOTER_DELETE', 'FOOTER_SHOW',
            'SOCIAL_INDEX', 'SOCIAL_CREATE', 'SOCIAL_EDIT', 'SOCIAL_DELETE', 'SOCIAL_SHOW',
            'PAYMENT_MEDIA_INDEX', 'PAYMENT_MEDIA_CREATE', 'PAYMENT_MEDIA_EDIT', 'PAYMENT_MEDIA_DELETE', 'PAYMENT_MEDIA_SHOW',
            'DIVISION_INDEX', 'DIVISION_CREATE', 'DIVISION_EDIT', 'DIVISION_DELETE', 'DIVISION_SHOW',
            'DISTRICT_INDEX', 'DISTRICT_CREATE', 'DISTRICT_EDIT', 'DISTRICT_DELETE', 'DISTRICT_SHOW',
            'THANA_INDEX', 'THANA_CREATE', 'THANA_EDIT', 'THANA_DELETE', 'THANA_SHOW',
            'SHIPPING_COST_INDEX', 'SHIPPING_COST_CREATE', 'SHIPPING_COST_EDIT', 'SHIPPING_COST_DELETE', 'SHIPPING_COST_SHOW',
            'ORDER_INDEX', 'ORDER_CREATE', 'ORDER_EDIT', 'ORDER_DELETE', 'ORDER_SHOW',
            'SERVICE_INDEX', 'SERVICE_CREATE', 'SERVICE_EDIT', 'SERVICE_DELETE', 'SERVICE_SHOW',
            'SHIPPING_CHART_INDEX', 'SHIPPING_CHART_CREATE', 'SHIPPING_CHART_EDIT', 'SHIPPING_CHART_DELETE', 'SHIPPING_CHART_SHOW',
            'CONTACT_MESSAGE_INDEX', 'CONTACT_MESSAGE_CREATE', 'CONTACT_MESSAGE_EDIT', 'CONTACT_MESSAGE_DELETE', 'CONTACT_MESSAGE_SHOW',
            'SERVICE_VIDEO_INDEX', 'SERVICE_VIDEO_CREATE', 'SERVICE_VIDEO_EDIT', 'SERVICE_VIDEO_DELETE', 'SERVICE_VIDEO_SHOW',

        ];
        foreach ($permissions as $key => $value) {
            Permission::query()->firstOrCreate(['name' => $value]);
        }
    }
}
