<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductFeature;
use App\Models\SliderImage;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public static function catalog(): array
    {
        return [
            [
                'category_slug' => 'honey',
                'slug' => 'litchi-flower-honey',
                'title_en' => 'Litchi Flower Honey',
                'title_bn' => 'Litchi Flower Honey',
                'badge_en' => 'Best Seller',
                'badge_bn' => 'Best Seller',
                'is_organic' => true,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'Light floral honey collected during the Rajshahi litchi bloom.',
                'short_desc_bn' => 'Light floral honey collected during the Rajshahi litchi bloom.',
                'description_en' => 'A clean and fragrant honey with a bright golden tone, smooth finish, and dependable everyday sweetness.',
                'description_bn' => 'A clean and fragrant honey with a bright golden tone, smooth finish, and dependable everyday sweetness.',
                'origin_story_en' => 'Collected during peak litchi bloom and filtered gently to preserve its floral aroma.',
                'origin_story_bn' => 'Collected during peak litchi bloom and filtered gently to preserve its floral aroma.',
                'conservation_en' => 'Store tightly closed in a cool and dry place. Do not refrigerate.',
                'conservation_bn' => 'Store tightly closed in a cool and dry place. Do not refrigerate.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Raw sourced', 'No added sugar', 'Everyday family pack'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 1,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'honey',
                'slug' => 'sundarban-wild-honey',
                'title_en' => 'Sundarban Wild Honey',
                'title_bn' => 'Sundarban Wild Honey',
                'badge_en' => 'Wild Collection',
                'badge_bn' => 'Wild Collection',
                'is_organic' => true,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'A deeper and richer wild honey profile sourced from forest regions.',
                'short_desc_bn' => 'A deeper and richer wild honey profile sourced from forest regions.',
                'description_en' => 'Bold raw honey with a woody aroma and dense texture, positioned as a premium choice for gifting and regular use.',
                'description_bn' => 'Bold raw honey with a woody aroma and dense texture, positioned as a premium choice for gifting and regular use.',
                'origin_story_en' => 'Collected from forest regions and packed to highlight its deep, raw character.',
                'origin_story_bn' => 'Collected from forest regions and packed to highlight its deep, raw character.',
                'conservation_en' => 'Keep away from direct sun and always use a dry spoon.',
                'conservation_bn' => 'Keep away from direct sun and always use a dry spoon.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Forest sourced', 'Premium gifting', 'Strong natural aroma'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 2,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'honey',
                'slug' => 'black-seed-honey',
                'title_en' => 'Black Seed Honey',
                'title_bn' => 'Black Seed Honey',
                'badge_en' => 'Premium',
                'badge_bn' => 'Premium',
                'is_organic' => true,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'A darker honey line with a stronger medicinal-style taste profile.',
                'short_desc_bn' => 'A darker honey line with a stronger medicinal-style taste profile.',
                'description_en' => 'Curated as a premium wellness-focused product with a rich finish and loyal repeat purchase appeal.',
                'description_bn' => 'Curated as a premium wellness-focused product with a rich finish and loyal repeat purchase appeal.',
                'origin_story_en' => 'A premium blend positioned for a richer taste profile and curated gifting.',
                'origin_story_bn' => 'A premium blend positioned for a richer taste profile and curated gifting.',
                'conservation_en' => 'Seal after each use and keep in a room-temperature shelf.',
                'conservation_bn' => 'Seal after each use and keep in a room-temperature shelf.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Premium line', 'Dense texture', 'Wellness focused'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 3,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'seasonal-fruits',
                'slug' => 'gopalbhog-mango',
                'title_en' => 'Gopalbhog Mango',
                'title_bn' => 'Gopalbhog Mango',
                'badge_en' => 'New Arrival',
                'badge_bn' => 'New Arrival',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'Sweet and aromatic mangoes presented as a seasonal hero product.',
                'short_desc_bn' => 'Sweet and aromatic mangoes presented as a seasonal hero product.',
                'description_en' => 'Soft, juicy mangoes selected for the homepage fruit slider with a clean, premium listing presentation.',
                'description_bn' => 'Soft, juicy mangoes selected for the homepage fruit slider with a clean, premium listing presentation.',
                'origin_story_en' => 'Selected from seasonal orchards and presented as a bright fruit hero for the homepage.',
                'origin_story_bn' => 'Selected from seasonal orchards and presented as a bright fruit hero for the homepage.',
                'conservation_en' => 'Keep in a cool room and consume within a few days after ripening.',
                'conservation_bn' => 'Keep in a cool room and consume within a few days after ripening.',
                'feature_image' => '/ui/images/mango.png',
                'hover_image' => '/ui/images/mango.png',
                'video_url' => null,
                'gallery' => ['/ui/images/mango.png', '/ui/images/mango.png'],
                'features' => ['Carbide free style listing', 'Seasonal hero product', 'Gift-friendly selection'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 4,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'seasonal-fruits',
                'slug' => 'fazli-mango',
                'title_en' => 'Fazli Mango',
                'title_bn' => 'Fazli Mango',
                'badge_en' => 'Seasonal',
                'badge_bn' => 'Seasonal',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'Large mangoes with a classic late-season profile and family pack appeal.',
                'short_desc_bn' => 'Large mangoes with a classic late-season profile and family pack appeal.',
                'description_en' => 'A dependable large-format fruit product positioned for bulk buying and attractive category-page merchandising.',
                'description_bn' => 'A dependable large-format fruit product positioned for bulk buying and attractive category-page merchandising.',
                'origin_story_en' => 'Large late-season mangoes curated for families and bulk buyers.',
                'origin_story_bn' => 'Large late-season mangoes curated for families and bulk buyers.',
                'conservation_en' => 'Allow to ripen naturally and keep in a breathable basket.',
                'conservation_bn' => 'Allow to ripen naturally and keep in a breathable basket.',
                'feature_image' => '/ui/images/mango.png',
                'hover_image' => '/ui/images/mango.png',
                'video_url' => null,
                'gallery' => ['/ui/images/mango.png', '/ui/images/mango.png'],
                'features' => ['Bulk friendly', 'Late season favorite', 'High pulp content'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 5,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'seasonal-fruits',
                'slug' => 'bombai-litchi',
                'title_en' => 'Bombai Litchi',
                'title_bn' => 'Bombai Litchi',
                'badge_en' => 'Pre-Order',
                'badge_bn' => 'Pre-Order',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => true,
                'is_top_selling' => false,
                'short_desc_en' => 'A bright seasonal fruit listing prepared as a fresh-arrival showcase item.',
                'short_desc_bn' => 'A bright seasonal fruit listing prepared as a fresh-arrival showcase item.',
                'description_en' => 'Presented as an upcoming fruit launch with strong homepage visual value and high click appeal.',
                'description_bn' => 'Presented as an upcoming fruit launch with strong homepage visual value and high click appeal.',
                'origin_story_en' => 'A seasonal fruit listing staged as a pre-order item with high visual appeal.',
                'origin_story_bn' => 'A seasonal fruit listing staged as a pre-order item with high visual appeal.',
                'conservation_en' => 'Keep chilled after delivery and consume quickly for best freshness.',
                'conservation_bn' => 'Keep chilled after delivery and consume quickly for best freshness.',
                'feature_image' => '/ui/images/mango.png',
                'hover_image' => '/ui/images/mango.png',
                'video_url' => null,
                'gallery' => ['/ui/images/mango.png', '/ui/images/mango.png'],
                'features' => ['Fresh arrival focus', 'Colorful seasonal item', 'High visual appeal'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 6,
                'season' => 'upcoming',
            ],
            [
                'category_slug' => 'premium-dates',
                'slug' => 'ajwa-dates',
                'title_en' => 'Ajwa Dates',
                'title_bn' => 'Ajwa Dates',
                'badge_en' => 'Imported',
                'badge_bn' => 'Imported',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'Premium imported dates positioned as a hero gifting and Ramadan-friendly product.',
                'short_desc_bn' => 'Premium imported dates positioned as a hero gifting and Ramadan-friendly product.',
                'description_en' => 'Soft and rich dates merchandised as a high-value staple with strong best-selling potential and premium pricing.',
                'description_bn' => 'Soft and rich dates merchandised as a high-value staple with strong best-selling potential and premium pricing.',
                'origin_story_en' => 'Curated as a premium imported date variety focused on gifting and everyday snacking.',
                'origin_story_bn' => 'Curated as a premium imported date variety focused on gifting and everyday snacking.',
                'conservation_en' => 'Keep airtight and away from heat to preserve softness.',
                'conservation_bn' => 'Keep airtight and away from heat to preserve softness.',
                'feature_image' => '/ui/images/dates.png',
                'hover_image' => '/ui/images/dates.png',
                'video_url' => null,
                'gallery' => ['/ui/images/dates.png', '/ui/images/dates.png'],
                'features' => ['Imported premium line', 'Gift-ready', 'Soft texture'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 7,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'premium-dates',
                'slug' => 'medjool-dates',
                'title_en' => 'Medjool Dates',
                'title_bn' => 'Medjool Dates',
                'badge_en' => 'Premium',
                'badge_bn' => 'Premium',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'Large and soft dates marketed as a premium indulgence line.',
                'short_desc_bn' => 'Large and soft dates marketed as a premium indulgence line.',
                'description_en' => 'A large-format imported dates product designed to round out the premium dry-fruits category.',
                'description_bn' => 'A large-format imported dates product designed to round out the premium dry-fruits category.',
                'origin_story_en' => 'Large premium dates presented to elevate the dry-fruits assortment.',
                'origin_story_bn' => 'Large premium dates presented to elevate the dry-fruits assortment.',
                'conservation_en' => 'Store in a sealed container to maintain texture.',
                'conservation_bn' => 'Store in a sealed container to maintain texture.',
                'feature_image' => '/ui/images/dates.png',
                'hover_image' => '/ui/images/dates.png',
                'video_url' => null,
                'gallery' => ['/ui/images/dates.png', '/ui/images/dates.png'],
                'features' => ['Large size fruit', 'Premium assortment', 'Soft caramel note'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 8,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'premium-dates',
                'slug' => 'sukkari-dates',
                'title_en' => 'Sukkari Dates',
                'title_bn' => 'Sukkari Dates',
                'badge_en' => 'New Arrival',
                'badge_bn' => 'New Arrival',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'A softer sweet dates line prepared as a new-arrival option.',
                'short_desc_bn' => 'A softer sweet dates line prepared as a new-arrival option.',
                'description_en' => 'A lighter premium dates option curated for assortment depth and new-arrival visibility.',
                'description_bn' => 'A lighter premium dates option curated for assortment depth and new-arrival visibility.',
                'origin_story_en' => 'A softer sweet date variety positioned as a new arrival for assortment depth.',
                'origin_story_bn' => 'A softer sweet date variety positioned as a new arrival for assortment depth.',
                'conservation_en' => 'Keep dry, sealed, and out of direct heat.',
                'conservation_bn' => 'Keep dry, sealed, and out of direct heat.',
                'feature_image' => '/ui/images/dates.png',
                'hover_image' => '/ui/images/dates.png',
                'video_url' => null,
                'gallery' => ['/ui/images/dates.png', '/ui/images/dates.png'],
                'features' => ['Soft sweet profile', 'New arrival assortment', 'Snacking friendly'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 9,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'cooking-essentials',
                'slug' => 'deshi-gawa-ghee',
                'title_en' => 'Deshi Gawa Ghee',
                'title_bn' => 'Deshi Gawa Ghee',
                'badge_en' => 'Top Selling',
                'badge_bn' => 'Top Selling',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'A premium ghee listing for daily cooking, gifting, and festival demand.',
                'short_desc_bn' => 'A premium ghee listing for daily cooking, gifting, and festival demand.',
                'description_en' => 'Rich and aromatic ghee positioned as a flagship pantry product with repeat-purchase value.',
                'description_bn' => 'Rich and aromatic ghee positioned as a flagship pantry product with repeat-purchase value.',
                'origin_story_en' => 'A pantry flagship product curated for aroma, richness, and repeat purchase.',
                'origin_story_bn' => 'A pantry flagship product curated for aroma, richness, and repeat purchase.',
                'conservation_en' => 'Store in a cool shelf and always use a clean spoon.',
                'conservation_bn' => 'Store in a cool shelf and always use a clean spoon.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Pantry essential', 'Premium aroma', 'Repeat-purchase item'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 10,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'cooking-essentials',
                'slug' => 'cold-pressed-mustard-oil',
                'title_en' => 'Cold Pressed Mustard Oil',
                'title_bn' => 'Cold Pressed Mustard Oil',
                'badge_en' => 'Daily Essential',
                'badge_bn' => 'Daily Essential',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'A kitchen staple listing with a trusted everyday positioning.',
                'short_desc_bn' => 'A kitchen staple listing with a trusted everyday positioning.',
                'description_en' => 'A strong everyday category anchor product for households that prefer traditional cooking essentials.',
                'description_bn' => 'A strong everyday category anchor product for households that prefer traditional cooking essentials.',
                'origin_story_en' => 'Cold pressed-style listing positioned as an everyday kitchen staple.',
                'origin_story_bn' => 'Cold pressed-style listing positioned as an everyday kitchen staple.',
                'conservation_en' => 'Keep the bottle closed and store away from direct heat.',
                'conservation_bn' => 'Keep the bottle closed and store away from direct heat.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Daily kitchen staple', 'Strong category anchor', 'Traditional cooking use'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 11,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'spices',
                'slug' => 'red-chilli-powder',
                'title_en' => 'Red Chilli Powder',
                'title_bn' => 'Red Chilli Powder',
                'badge_en' => 'Best Seller',
                'badge_bn' => 'Best Seller',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'A vivid spice listing built for strong category-level conversion.',
                'short_desc_bn' => 'A vivid spice listing built for strong category-level conversion.',
                'description_en' => 'Bright, bold, and easy to merchandise, this spice line supports both everyday and premium pack sizes.',
                'description_bn' => 'Bright, bold, and easy to merchandise, this spice line supports both everyday and premium pack sizes.',
                'origin_story_en' => 'A bright spice staple designed for strong shelf and category presence.',
                'origin_story_bn' => 'A bright spice staple designed for strong shelf and category presence.',
                'conservation_en' => 'Store in an airtight jar in a dry cabinet.',
                'conservation_bn' => 'Store in an airtight jar in a dry cabinet.',
                'feature_image' => '/ui/images/spices.png',
                'hover_image' => '/ui/images/spices.png',
                'video_url' => null,
                'gallery' => ['/ui/images/spices.png', '/ui/images/spices.png'],
                'features' => ['Fresh ground look', 'Strong shelf appeal', 'Daily cooking staple'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 12,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'spices',
                'slug' => 'turmeric-powder',
                'title_en' => 'Turmeric Powder',
                'title_bn' => 'Turmeric Powder',
                'badge_en' => 'Featured',
                'badge_bn' => 'Featured',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'A clean everyday spice listing for the pantry essentials category.',
                'short_desc_bn' => 'A clean everyday spice listing for the pantry essentials category.',
                'description_en' => 'Well-positioned as a dependable kitchen staple with approachable pricing and broad demand.',
                'description_bn' => 'Well-positioned as a dependable kitchen staple with approachable pricing and broad demand.',
                'origin_story_en' => 'An everyday pantry spice designed for broad household demand.',
                'origin_story_bn' => 'An everyday pantry spice designed for broad household demand.',
                'conservation_en' => 'Keep tightly sealed and away from moisture.',
                'conservation_bn' => 'Keep tightly sealed and away from moisture.',
                'feature_image' => '/ui/images/spices.png',
                'hover_image' => '/ui/images/spices.png',
                'video_url' => null,
                'gallery' => ['/ui/images/spices.png', '/ui/images/spices.png'],
                'features' => ['Everyday pantry line', 'Approachable price point', 'Clean category coverage'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 13,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'spices',
                'slug' => 'shahi-garam-masala',
                'title_en' => 'Shahi Garam Masala',
                'title_bn' => 'Shahi Garam Masala',
                'badge_en' => 'New Arrival',
                'badge_bn' => 'New Arrival',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => false,
                'short_desc_en' => 'A premium blended masala positioned as a signature spice product.',
                'short_desc_bn' => 'A premium blended masala positioned as a signature spice product.',
                'description_en' => 'A richer spice assortment item designed to lift the category with premium flavor positioning.',
                'description_bn' => 'A richer spice assortment item designed to lift the category with premium flavor positioning.',
                'origin_story_en' => 'A premium blended masala curated as a signature category item.',
                'origin_story_bn' => 'A premium blended masala curated as a signature category item.',
                'conservation_en' => 'Keep sealed and use within a few months for best aroma.',
                'conservation_bn' => 'Keep sealed and use within a few months for best aroma.',
                'feature_image' => '/ui/images/spices.png',
                'hover_image' => '/ui/images/spices.png',
                'video_url' => null,
                'gallery' => ['/ui/images/spices.png', '/ui/images/spices.png'],
                'features' => ['Signature spice line', 'Premium blend', 'Gift-ready jar option'],
                'status' => true,
                'is_free_shipping' => false,
                'sort_order' => 14,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'nuts-dry-fruits',
                'slug' => 'premium-cashew-nuts',
                'title_en' => 'Premium Cashew Nuts',
                'title_bn' => 'Premium Cashew Nuts',
                'badge_en' => 'Best Seller',
                'badge_bn' => 'Best Seller',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'A polished dry-fruits listing with premium snack positioning.',
                'short_desc_bn' => 'A polished dry-fruits listing with premium snack positioning.',
                'description_en' => 'Curated as a premium snacking and gifting product with reliable category-wide appeal.',
                'description_bn' => 'Curated as a premium snacking and gifting product with reliable category-wide appeal.',
                'origin_story_en' => 'A premium snacking line positioned for gifting and dependable category conversion.',
                'origin_story_bn' => 'A premium snacking line positioned for gifting and dependable category conversion.',
                'conservation_en' => 'Store airtight and keep away from moisture.',
                'conservation_bn' => 'Store airtight and keep away from moisture.',
                'feature_image' => '/ui/images/dates.png',
                'hover_image' => '/ui/images/dates.png',
                'video_url' => null,
                'gallery' => ['/ui/images/dates.png', '/ui/images/dates.png'],
                'features' => ['Premium snack line', 'Gift-ready pack', 'Dry-fruits category anchor'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 15,
                'season' => 'ongoing',
            ],
            [
                'category_slug' => 'nuts-dry-fruits',
                'slug' => 'honey-nut-power-mix',
                'title_en' => 'Honey Nut Power Mix',
                'title_bn' => 'Honey Nut Power Mix',
                'badge_en' => 'Featured',
                'badge_bn' => 'Featured',
                'is_organic' => false,
                'is_sugar_free' => true,
                'is_pre_order' => false,
                'is_top_selling' => true,
                'short_desc_en' => 'A value-added snack blend built for top conversion and cross-category appeal.',
                'short_desc_bn' => 'A value-added snack blend built for top conversion and cross-category appeal.',
                'description_en' => 'A mixed snack product designed to combine the honey and dry-fruits story into one premium listing.',
                'description_bn' => 'A mixed snack product designed to combine the honey and dry-fruits story into one premium listing.',
                'origin_story_en' => 'A curated mix designed to connect honey and dry-fruit stories in one premium pouch.',
                'origin_story_bn' => 'A curated mix designed to connect honey and dry-fruit stories in one premium pouch.',
                'conservation_en' => 'Keep sealed after opening and avoid humid storage.',
                'conservation_bn' => 'Keep sealed after opening and avoid humid storage.',
                'feature_image' => '/ui/images/honey.png',
                'hover_image' => '/ui/images/honey.png',
                'video_url' => null,
                'gallery' => ['/ui/images/honey.png', '/ui/images/honey.png'],
                'features' => ['Cross-category bestseller', 'Snack-ready blend', 'Premium pouch option'],
                'status' => true,
                'is_free_shipping' => true,
                'sort_order' => 16,
                'season' => 'ongoing',
            ],
        ];
    }

    public function run(): void
    {
        $categories = Category::query()
            ->select('id', 'slug')
            ->get()
            ->keyBy('slug');

        if ($categories->isEmpty()) {
            return;
        }

        foreach (self::catalog() as $item) {
            $category = $categories->get($item['category_slug']);

            if (! $category) {
                continue;
            }

            $product = Product::create([
                'category_id' => $category->id,
                'title_en' => $item['title_en'],
                'title_bn' => $item['title_bn'],
                'short_desc_en' => $item['short_desc_en'],
                'short_desc_bn' => $item['short_desc_bn'],
                'badge_en' => $item['badge_en'] ?? null,
                'badge_bn' => $item['badge_bn'] ?? null,
                'description_en' => $item['description_en'],
                'description_bn' => $item['description_bn'],
                'origin_story_en' => $item['origin_story_en'] ?? null,
                'origin_story_bn' => $item['origin_story_bn'] ?? null,
                'conservation_en' => $item['conservation_en'],
                'conservation_bn' => $item['conservation_bn'],
                'slug' => $item['slug'],
                'feature_image' => $item['feature_image'],
                'hover_image' => $item['hover_image'],
                'video_url' => $item['video_url'] ?? null,
                'status' => $item['status'],
                'is_free_shipping' => $item['is_free_shipping'],
                'is_organic' => (bool) ($item['is_organic'] ?? false),
                'is_sugar_free' => (bool) ($item['is_sugar_free'] ?? false),
                'is_pre_order' => (bool) ($item['is_pre_order'] ?? false),
                'is_top_selling' => (bool) ($item['is_top_selling'] ?? false),
                'sort_order' => $item['sort_order'],
                'season' => $item['season'],
            ]);

            foreach ($item['features'] as $feature) {
                ProductFeature::create([
                    'product_id' => $product->id,
                    'feature_en' => $feature,
                    'feature_bn' => $feature,
                ]);
            }

            foreach ($item['gallery'] as $image) {
                SliderImage::create([
                    'product_id' => $product->id,
                    'slider_image' => $image,
                ]);
            }
        }
    }
}
