<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class ThanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districtsThanas = [
            'Dhaka' => [
                ['name' => 'Adabor', 'bn_name' => 'আদাবর'],
                ['name' => 'Badda', 'bn_name' => 'বাড্ডা'],
                ['name' => 'Bangshal', 'bn_name' => 'বংশাল'],
                ['name' => 'Bimanbandar', 'bn_name' => 'বিমানবন্দর'],
                ['name' => 'Cantonment', 'bn_name' => 'ক্যান্টনমেন্ট'],
                ['name' => 'Chawkbazar', 'bn_name' => 'চকবাজার'],
                ['name' => 'Dakshinkhan', 'bn_name' => 'দক্ষিণখান'],
                ['name' => 'Darus Salam', 'bn_name' => 'দারুস সালাম'],
                ['name' => 'Demra', 'bn_name' => 'ডেমরা'],
                ['name' => 'Dhamrai', 'bn_name' => 'ধামরাই'],
                ['name' => 'Dhanmondi', 'bn_name' => 'ধানমন্ডি'],
                ['name' => 'Dohar', 'bn_name' => 'দোহার'],
                ['name' => 'Gendaria', 'bn_name' => 'গেন্ডারিয়া'],
                ['name' => 'Gulshan', 'bn_name' => 'গুলশান'],
                ['name' => 'Hazaribagh', 'bn_name' => 'হাজারীবাগ'],
                ['name' => 'Jatrabari', 'bn_name' => 'যাত্রাবাড়ী'],
                ['name' => 'Kadamtali', 'bn_name' => 'কদমতলী'],
                ['name' => 'Kafrul', 'bn_name' => 'কাফরুল'],
                ['name' => 'Kalabagan', 'bn_name' => 'কলাবাগান'],
                ['name' => 'Kamrangirchar', 'bn_name' => 'কামরাঙ্গীরচর'],
                ['name' => 'Keraniganj', 'bn_name' => 'কেরানীগঞ্জ'],
                ['name' => 'Khilgaon', 'bn_name' => 'খিলগাঁও'],
                ['name' => 'Khilkhet', 'bn_name' => 'খিলক্ষেত'],
                ['name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী'],
                ['name' => 'Lalbagh', 'bn_name' => 'লালবাগ'],
                ['name' => 'Mirpur', 'bn_name' => 'মিরপুর'],
                ['name' => 'Mohammadpur', 'bn_name' => 'মোহাম্মদপুর'],
                ['name' => 'Motijheel', 'bn_name' => 'মতিঝিল'],
                ['name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ'],
                ['name' => 'New Market', 'bn_name' => 'নিউ মার্কেট'],
                ['name' => 'Pallabi', 'bn_name' => 'পল্লবী'],
                ['name' => 'Paltan', 'bn_name' => 'পল্টন'],
                ['name' => 'Ramna', 'bn_name' => 'রমনা'],
                ['name' => 'Rampura', 'bn_name' => 'রামপুরা'],
                ['name' => 'Sabujbagh', 'bn_name' => 'সবুজবাগ'],
                ['name' => 'Savar', 'bn_name' => 'সাভার'],
                ['name' => 'Shah Ali', 'bn_name' => 'শাহ আলী'],
                ['name' => 'Shahbag', 'bn_name' => 'শাহবাগ'],
                ['name' => 'Sher-e-Bangla Nagar', 'bn_name' => 'শেরেবাংলা নগর'],
                ['name' => 'Shyampur', 'bn_name' => 'শ্যামপুর'],
                ['name' => 'Sutrapur', 'bn_name' => 'সূত্রাপুর'],
                ['name' => 'Tejgaon', 'bn_name' => 'তেজগাঁও'],
                ['name' => 'Tejgaon Industrial Area', 'bn_name' => 'তেজগাঁও শিল্প এলাকা'],
                ['name' => 'Turag', 'bn_name' => 'তুরাগ'],
                ['name' => 'Uttara', 'bn_name' => 'উত্তরা'],
                ['name' => 'Uttarkhan', 'bn_name' => 'উত্তরখান'],
                ['name' => 'Vatara', 'bn_name' => 'ভাটারা'],
                ['name' => 'Wari', 'bn_name' => 'ওয়ারী'],
            ],
            'Gazipur' => [
                ['name' => 'Gazipur Sadar', 'bn_name' => 'গাজীপুর সদর'],
                ['name' => 'Kaliakair', 'bn_name' => 'কালিয়াকৈর'],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
                ['name' => 'Kapasia', 'bn_name' => 'কাপাসিয়া'],
                ['name' => 'Sreepur', 'bn_name' => 'শ্রীপুর'],
                ['name' => 'Tongi', 'bn_name' => 'টঙ্গী'],
            ],
            'Chittagong' => [
                ['name' => 'Anwara', 'bn_name' => 'আনোয়ারা'],
                ['name' => 'Bakalia', 'bn_name' => 'বাকলিয়া'],
                ['name' => 'Banshkhali', 'bn_name' => 'বাঁশখালী'],
                ['name' => 'Bayazid Bostami', 'bn_name' => 'বায়েজিদ বোস্তামী'],
                ['name' => 'Boalkhali', 'bn_name' => 'বোয়ালখালী'],
                ['name' => 'Chandanaish', 'bn_name' => 'চন্দনাইশ'],
                ['name' => 'Chandgaon', 'bn_name' => 'চান্দগাঁও'],
                ['name' => 'Chawkbazar', 'bn_name' => 'চকবাজার'],
                ['name' => 'Double Mooring', 'bn_name' => 'ডবল মুরিং'],
                ['name' => 'Fatikchhari', 'bn_name' => 'ফটিকছড়ি'],
                ['name' => 'Halishahar', 'bn_name' => 'হালিশহর'],
                ['name' => 'Hathazari', 'bn_name' => 'হাটহাজারী'],
                ['name' => 'Karnafuli', 'bn_name' => 'কর্ণফুলী'],
                ['name' => 'Khulshi', 'bn_name' => 'খুলশী'],
                ['name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী'],
                ['name' => 'Lohagara', 'bn_name' => 'লোহাগাড়া'],
                ['name' => 'Mirsharai', 'bn_name' => 'মীরসরাই'],
                ['name' => 'Pahartali', 'bn_name' => 'পাহাড়তলী'],
                ['name' => 'Panchlaish', 'bn_name' => 'পাঁচলাইশ'],
                ['name' => 'Patenga', 'bn_name' => 'পতেঙ্গা'],
                ['name' => 'Patiya', 'bn_name' => 'পটিয়া'],
                ['name' => 'Rangunia', 'bn_name' => 'রাঙ্গুনিয়া'],
                ['name' => 'Raozan', 'bn_name' => 'রাউজান'],
                ['name' => 'Sandwip', 'bn_name' => 'সন্দ্বীপ'],
                ['name' => 'Satkania', 'bn_name' => 'সাতকানিয়া'],
                ['name' => 'Sitakunda', 'bn_name' => 'সীতাকুণ্ড'],
            ],
            'Narayanganj' => [
                ['name' => 'Araihazar', 'bn_name' => 'আড়াইহাজার'],
                ['name' => 'Bandar', 'bn_name' => 'বন্দর'],
                ['name' => 'Narayanganj Sadar', 'bn_name' => 'নারায়ণগঞ্জ সদর'],
                ['name' => 'Rupganj', 'bn_name' => 'রূপগঞ্জ'],
                ['name' => 'Sonargaon', 'bn_name' => 'সোনারগাঁও'],
            ],
            'Comilla' => [
                ['name' => 'Barura', 'bn_name' => 'বরুড়া'],
                ['name' => 'Brahmanpara', 'bn_name' => 'ব্রাহ্মণপাড়া'],
                ['name' => 'Burichang', 'bn_name' => 'বুড়িচং'],
                ['name' => 'Chandina', 'bn_name' => 'চান্দিনা'],
                ['name' => 'Chauddagram', 'bn_name' => 'চৌদ্দগ্রাম'],
                ['name' => 'Comilla Sadar', 'bn_name' => 'কুমিল্লা সদর'],
                ['name' => 'Comilla Sadar Dakshin', 'bn_name' => 'কুমিল্লা সদর দক্ষিণ'],
                ['name' => 'Daudkandi', 'bn_name' => 'দাউদকান্দি'],
                ['name' => 'Debidwar', 'bn_name' => 'দেবিদ্বার'],
                ['name' => 'Homna', 'bn_name' => 'হোমনা'],
                ['name' => 'Laksam', 'bn_name' => 'লাকসাম'],
                ['name' => 'Lalmai', 'bn_name' => 'লালমাই'],
                ['name' => 'Manoharganj', 'bn_name' => 'মনোহরগঞ্জ'],
                ['name' => 'Meghna', 'bn_name' => 'মেঘনা'],
                ['name' => 'Muradnagar', 'bn_name' => 'মুরাদনগর'],
                ['name' => 'Nangalkot', 'bn_name' => 'নাঙ্গলকোট'],
                ['name' => 'Titas', 'bn_name' => 'তিতাস'],
            ],
            "Cox's Bazar" => [
                ['name' => 'Chakaria', 'bn_name' => 'চকোরিয়া'],
                ['name' => "Cox's Bazar Sadar", 'bn_name' => 'কক্সবাজার সদর'],
                ['name' => 'Kutubdia', 'bn_name' => 'কুতুবদিয়া'],
                ['name' => 'Maheshkhali', 'bn_name' => 'মহেশখালী'],
                ['name' => 'Pekua', 'bn_name' => 'পেকুয়া'],
                ['name' => 'Ramu', 'bn_name' => 'রামু'],
                ['name' => 'Teknaf', 'bn_name' => 'টেকনাফ'],
                ['name' => 'Ukhiya', 'bn_name' => 'উখিয়া'],
            ],
            'Rajshahi' => [
                ['name' => 'Bagha', 'bn_name' => 'বাঘা'],
                ['name' => 'Bagmara', 'bn_name' => 'বাগমারা'],
                ['name' => 'Charghat', 'bn_name' => 'চারঘাট'],
                ['name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর'],
                ['name' => 'Godagari', 'bn_name' => 'গোদাগাড়ী'],
                ['name' => 'Mohanpur', 'bn_name' => 'মোহনপুর'],
                ['name' => 'Paba', 'bn_name' => 'পবা'],
                ['name' => 'Puthia', 'bn_name' => 'পুঠিয়া'],
                ['name' => 'Tanore', 'bn_name' => 'তানোর'],
            ],
            'Khulna' => [
                ['name' => 'Batiaghata', 'bn_name' => 'বটিয়াঘাটা'],
                ['name' => 'Dacope', 'bn_name' => 'দাকোপ'],
                ['name' => 'Dumuria', 'bn_name' => 'ডুমুরিয়া'],
                ['name' => 'Dighalia', 'bn_name' => 'দিঘলিয়া'],
                ['name' => 'Koyra', 'bn_name' => 'কয়রা'],
                ['name' => 'Paikgachha', 'bn_name' => 'পাইকগাছা'],
                ['name' => 'Phultala', 'bn_name' => 'ফুলতলা'],
                ['name' => 'Rupsha', 'bn_name' => 'রূপসা'],
                ['name' => 'Terokhada', 'bn_name' => 'তেরখাদা'],
                ['name' => 'Khulna Sadar', 'bn_name' => 'খুলনা সদর'],
                ['name' => 'Khalishpur', 'bn_name' => 'খালিশপুর'],
                ['name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],
                ['name' => 'Sonadanga', 'bn_name' => 'সোনাডাঙ্গা'],
                ['name' => 'Khan Jahan Ali', 'bn_name' => 'খান জাহান আলী'],
            ],
            'Barisal' => [
                ['name' => 'Agailjhara', 'bn_name' => 'আগৈলঝাড়া'],
                ['name' => 'Babuganj', 'bn_name' => 'বাবুগঞ্জ'],
                ['name' => 'Bakerganj', 'bn_name' => 'বাকেরগঞ্জ'],
                ['name' => 'Banaripara', 'bn_name' => 'বানারীপাড়া'],
                ['name' => 'Gaurnadi', 'bn_name' => 'গৌরনদী'],
                ['name' => 'Hizla', 'bn_name' => 'হিজলা'],
                ['name' => 'Barisal Sadar', 'bn_name' => 'বরিশাল সদর'],
                ['name' => 'Mehendiganj', 'bn_name' => 'মেহেন্দিগঞ্জ'],
                ['name' => 'Muladi', 'bn_name' => 'মুলাদী'],
                ['name' => 'Wazirpur', 'bn_name' => 'উজিরপুর'],
            ],
            'Sylhet' => [
                ['name' => 'Balaganj', 'bn_name' => 'বালাগঞ্জ'],
                ['name' => 'Beanibazar', 'bn_name' => 'বিয়ানীবাজার'],
                ['name' => 'Bishwamvarpur', 'bn_name' => 'বিশ্বনাথ'],
                ['name' => 'Companiganj', 'bn_name' => 'কোম্পানীগঞ্জ'],
                ['name' => 'Fenchuganj', 'bn_name' => 'ফেঞ্চুগঞ্জ'],
                ['name' => 'Golapganj', 'bn_name' => 'গোলাপগঞ্জ'],
                ['name' => 'Gowainghat', 'bn_name' => 'গোয়াইনঘাট'],
                ['name' => 'Jaintiapur', 'bn_name' => 'জৈন্তাপুর'],
                ['name' => 'Kanaighat', 'bn_name' => 'কানাইঘাট'],
                ['name' => 'Osmani Nagar', 'bn_name' => 'ওসমানী নগর'],
                ['name' => 'Sylhet Sadar', 'bn_name' => 'সিলেট সদর'],
                ['name' => 'Zakiganj', 'bn_name' => 'জকিগঞ্জ'],
                ['name' => 'Dakshin Surma', 'bn_name' => 'দক্ষিণ সুরমা'],
            ],
            'Rangpur' => [
                ['name' => 'Badarganj', 'bn_name' => 'বদরগঞ্জ'],
                ['name' => 'Gangachara', 'bn_name' => 'গঙ্গাচড়া'],
                ['name' => 'Kaunia', 'bn_name' => 'কাউনিয়া'],
                ['name' => 'Rangpur Sadar', 'bn_name' => 'রংপুর সদর'],
                ['name' => 'Mithapukur', 'bn_name' => 'মিঠাপুকুর'],
                ['name' => 'Pirgachha', 'bn_name' => 'পীরগাছা'],
                ['name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ'],
                ['name' => 'Taraganj', 'bn_name' => 'তারাগঞ্জ'],
            ],
            'Mymensingh' => [
                ['name' => 'Bhaluka', 'bn_name' => 'ভালুকা'],
                ['name' => 'Dhobaura', 'bn_name' => 'ধোবাউড়া'],
                ['name' => 'Fulbaria', 'bn_name' => 'ফুলবাড়িয়া'],
                ['name' => 'Gaffargaon', 'bn_name' => 'গফরগাঁও'],
                ['name' => 'Gauripur', 'bn_name' => 'গৌরীপুর'],
                ['name' => 'Haluaghat', 'bn_name' => 'হালুয়াঘাট'],
                ['name' => 'Ishwarganj', 'bn_name' => 'ঈশ্বরগঞ্জ'],
                ['name' => 'Mymensingh Sadar', 'bn_name' => 'ময়মনসিংহ সদর'],
                ['name' => 'Muktagachha', 'bn_name' => 'মুক্তাগাছা'],
                ['name' => 'Nandail', 'bn_name' => 'নান্দাইল'],
                ['name' => 'Phulpur', 'bn_name' => 'ফুলপুর'],
                ['name' => 'Trishal', 'bn_name' => 'ত্রিশাল'],
                ['name' => 'Tara Khanda', 'bn_name' => 'তারাকান্দা'],
            ],
            // Add other districts as needed with generic loop for remaining districts if strict detailed list is not available for all 64
        ];

        // Generic placeholders for other districts to ensure we have coverage if needed,
        // but for now, we will stick to the provided detailed ones and add more.
        // Expanding to other major districts:

        $moreDistricts = [
            'Bogra' => [
                ['name' => 'Adamdighi', 'bn_name' => 'আদমদিঘী'],
                ['name' => 'Bogra Sadar', 'bn_name' => 'বগুড়া সদর'],
                ['name' => 'Dhunat', 'bn_name' => 'ধুনট'],
                ['name' => 'Dupchanchia', 'bn_name' => 'দুপচাঁচিয়া'],
                ['name' => 'Gabtali', 'bn_name' => 'গাবতলী'],
                ['name' => 'Kahaloo', 'bn_name' => 'কাহালু'],
                ['name' => 'Nandigram', 'bn_name' => 'নন্দীগ্রাম'],
                ['name' => 'Sariakandi', 'bn_name' => 'সারিয়াকান্দি'],
                ['name' => 'Shajahanpur', 'bn_name' => 'শাজাহানপুর'],
                ['name' => 'Sherpur', 'bn_name' => 'শেরপুর'],
                ['name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ'],
                ['name' => 'Sonatala', 'bn_name' => 'সোনাতলা'],
            ],
            'Pabna' => [
                ['name' => 'Atgharia', 'bn_name' => 'আটঘরিয়া'],
                ['name' => 'Bera', 'bn_name' => 'বেড়া'],
                ['name' => 'Bhangura', 'bn_name' => 'ভাঙ্গুড়া'],
                ['name' => 'Chatmohar', 'bn_name' => 'চাটমোহর'],
                ['name' => 'Faridpur', 'bn_name' => 'ফরিদপুর'],
                ['name' => 'Ishwardi', 'bn_name' => 'ঈশ্বরদী'],
                ['name' => 'Pabna Sadar', 'bn_name' => 'পাবনা সদর'],
                ['name' => 'Santhia', 'bn_name' => 'সাঁথিয়া'],
                ['name' => 'Sujanagar', 'bn_name' => 'সুজানগর'],
            ],
            'Tangail' => [
                ['name' => 'Basail', 'bn_name' => 'বাসাইল'],
                ['name' => 'Bhuapur', 'bn_name' => 'ভূঞাপুর'],
                ['name' => 'Delduar', 'bn_name' => 'দেলদুয়ার'],
                ['name' => 'Dhanbari', 'bn_name' => 'ধনবাড়ী'],
                ['name' => 'Ghatail', 'bn_name' => 'ঘাটাইল'],
                ['name' => 'Gopalpur', 'bn_name' => 'গোপালপুর'],
                ['name' => 'Kalihati', 'bn_name' => 'কালিহাতী'],
                ['name' => 'Madhupur', 'bn_name' => 'মধুপুর'],
                ['name' => 'Mirzapur', 'bn_name' => 'মির্জাপুর'],
                ['name' => 'Nagarpur', 'bn_name' => 'নাগরপুর'],
                ['name' => 'Sakhipur', 'bn_name' => 'সখিপুর'],
                ['name' => 'Tangail Sadar', 'bn_name' => 'টাঙ্গাইল সদর'],
            ],
            'Faridpur' => [
                ['name' => 'Alfadanga', 'bn_name' => 'আলফাডাঙ্গা'],
                ['name' => 'Bhanga', 'bn_name' => 'ভাঙ্গা'],
                ['name' => 'Boalmari', 'bn_name' => 'বোয়ালমারী'],
                ['name' => 'Charbhadrasan', 'bn_name' => 'চরভদ্রাসন'],
                ['name' => 'Faridpur Sadar', 'bn_name' => 'ফরিদপুর সদর'],
                ['name' => 'Madhukhali', 'bn_name' => 'মধুখালী'],
                ['name' => 'Nagarkanda', 'bn_name' => 'নগরকান্দা'],
                ['name' => 'Sadarpur', 'bn_name' => 'সদরপুর'],
                ['name' => 'Saltha', 'bn_name' => 'সালথা'],
            ],
            'Jessore' => [
                ['name' => 'Abhaynagar', 'bn_name' => 'অভয়নগর'],
                ['name' => 'Bagherpara', 'bn_name' => 'বাঘারপাড়া'],
                ['name' => 'Chaugachha', 'bn_name' => 'চৌগাছা'],
                ['name' => 'Jhikargachha', 'bn_name' => 'ঝিকরগাছা'],
                ['name' => 'Keshabpur', 'bn_name' => 'কেশবপুর'],
                ['name' => 'Jessore Sadar', 'bn_name' => 'যশোর সদর'],
                ['name' => 'Manirampur', 'bn_name' => 'মণিরামপুর'],
                ['name' => 'Sharsha', 'bn_name' => 'শার্শা'],
            ],
            'Kushtia' => [
                ['name' => 'Bheramara', 'bn_name' => 'ভেড়ামারা'],
                ['name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],
                ['name' => 'Khoksa', 'bn_name' => 'খোকসা'],
                ['name' => 'Kumarkhali', 'bn_name' => 'কুমারখালী'],
                ['name' => 'Kushtia Sadar', 'bn_name' => 'কুষ্টিয়া সদর'],
                ['name' => 'Mirpur', 'bn_name' => 'মিরপুর'],
            ],
            'Dinajpur' => [
                ['name' => 'Birampur', 'bn_name' => 'বিরামপুর'],
                ['name' => 'Birganj', 'bn_name' => 'বীরগঞ্জ'],
                ['name' => 'Biral', 'bn_name' => 'বিরল'],
                ['name' => 'Bochaganj', 'bn_name' => 'বোচাগঞ্জ'],
                ['name' => 'Chirirbandar', 'bn_name' => 'চিরিরবন্দর'],
                ['name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ী'],
                ['name' => 'Ghoraghat', 'bn_name' => 'ঘোড়াঘাট'],
                ['name' => 'Hakimpur', 'bn_name' => 'হাকিমপুর'],
                ['name' => 'Kaharole', 'bn_name' => 'কাহারোল'],
                ['name' => 'Khansama', 'bn_name' => 'খানসামা'],
                ['name' => 'Dinajpur Sadar', 'bn_name' => 'দিনাজপুর সদর'],
                ['name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ'],
                ['name' => 'Parbatipur', 'bn_name' => 'পার্বতীপুর'],
            ],
            'Noakhali' => [
                ['name' => 'Begumganj', 'bn_name' => 'বেগমগঞ্জ'],
                ['name' => 'Chatkhil', 'bn_name' => 'চাটখিল'],
                ['name' => 'Companiganj', 'bn_name' => 'কোম্পানীগঞ্জ'],
                ['name' => 'Hatiya', 'bn_name' => 'হাতিয়া'],
                ['name' => 'Kabirhat', 'bn_name' => 'কবিরহাট'],
                ['name' => 'Senbagh', 'bn_name' => 'সেনবাগ'],
                ['name' => 'Sonaimuri', 'bn_name' => 'সোনাইমুড়ী'],
                ['name' => 'Subarnachar', 'bn_name' => 'সুবর্ণচর'],
                ['name' => 'Noakhali Sadar', 'bn_name' => 'নোয়াখালী সদর'],
            ],
            'Feni' => [
                ['name' => 'Chhagalnaiya', 'bn_name' => 'ছাগলনাইয়ার'],
                ['name' => 'Daganbhuiyan', 'bn_name' => 'দাগনভূঁইয়া'],
                ['name' => 'Feni Sadar', 'bn_name' => 'ফেনী সদর'],
                ['name' => 'Parshuram', 'bn_name' => 'পরশুরাম'],
                ['name' => 'Fulgazi', 'bn_name' => 'ফুলগাজী'],
                ['name' => 'Sonagazi', 'bn_name' => 'সোনাগাজী'],
            ],
            'Chandpur' => [
                ['name' => 'Chandpur Sadar', 'bn_name' => 'চাঁদপুর সদর'],
                ['name' => 'Faridganj', 'bn_name' => 'ফরিদগঞ্জ'],
                ['name' => 'Haimchar', 'bn_name' => 'হাইমচর'],
                ['name' => 'Haziganj', 'bn_name' => 'হাজীগঞ্জ'],
                ['name' => 'Kachua', 'bn_name' => 'কচুয়া'],
                ['name' => 'Matlab Dakshin', 'bn_name' => 'মতলব দক্ষিণ'],
                ['name' => 'Matlab Uttar', 'bn_name' => 'মতলব উত্তর'],
                ['name' => 'Shahrasti', 'bn_name' => 'শাহরাস্তি'],
            ],
            'Brahmanbaria' => [
                ['name' => 'Akhaura', 'bn_name' => 'আখাউড়া'],
                ['name' => 'Ashuganj', 'bn_name' => 'আশুগঞ্জ'],
                ['name' => 'Bancharampur', 'bn_name' => 'বাঞ্ছারামপুর'],
                ['name' => 'Bijoynagar', 'bn_name' => 'বিজয়নগর'],
                ['name' => 'Brahmanbaria Sadar', 'bn_name' => 'ব্রাহ্মণবাড়িয়া সদর'],
                ['name' => 'Kasba', 'bn_name' => 'কসবা'],
                ['name' => 'Nabinagar', 'bn_name' => 'নবীনগর'],
                ['name' => 'Nasirnagar', 'bn_name' => 'নাসিরনগর'],
                ['name' => 'Sarail', 'bn_name' => 'সরাইল'],
            ],
            'Lakshmipur' => [
                ['name' => 'Kamalnagar', 'bn_name' => 'কমলনগর'],
                ['name' => 'Lakshmipur Sadar', 'bn_name' => 'লক্ষ্মীপুর সদর'],
                ['name' => 'Raipur', 'bn_name' => 'রায়পুর'],
                ['name' => 'Ramganj', 'bn_name' => 'রামগঞ্জ'],
                ['name' => 'Ramgati', 'bn_name' => 'রামগতি'],
            ],
            'Jamalpur' => [
                ['name' => 'Baksiganj', 'bn_name' => 'বকশীগঞ্জ'],
                ['name' => 'Dewanganj', 'bn_name' => 'দেওয়ানগঞ্জ'],
                ['name' => 'Islampur', 'bn_name' => 'ইসলামপুর'],
                ['name' => 'Jamalpur Sadar', 'bn_name' => 'জামালপুর সদর'],
                ['name' => 'Madarganj', 'bn_name' => 'মাদারগঞ্জ'],
                ['name' => 'Melandaha', 'bn_name' => 'মেলান্দহ'],
                ['name' => 'Sarishabari', 'bn_name' => 'সরিষাবাড়ী'],
            ],
            'Kishoreganj' => [
                ['name' => 'Austagram', 'bn_name' => 'অষ্টগ্রাম'],
                ['name' => 'Bajitpur', 'bn_name' => 'বাজিতপুর'],
                ['name' => 'Bhairab', 'bn_name' => 'ভৈরব'],
                ['name' => 'Hossainpur', 'bn_name' => 'হোসেনপুর'],
                ['name' => 'Itna', 'bn_name' => 'ইটনা'],
                ['name' => 'Karimganj', 'bn_name' => 'করিমগঞ্জ'],
                ['name' => 'Katiadi', 'bn_name' => 'কটিয়াদী'],
                ['name' => 'Kishoreganj Sadar', 'bn_name' => 'কিশোরগঞ্জ সদর'],
                ['name' => 'Kuliarchar', 'bn_name' => 'কুলিয়ারচর'],
                ['name' => 'Mithamain', 'bn_name' => 'মিঠামইন'],
                ['name' => 'Nikli', 'bn_name' => 'নিকলী'],
                ['name' => 'Pakundia', 'bn_name' => 'পাকুন্দিয়া'],
                ['name' => 'Tarail', 'bn_name' => 'তাড়াইল'],
            ],
            'Manikganj' => [
                ['name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর'],
                ['name' => 'Ghior', 'bn_name' => 'ঘিওর'],
                ['name' => 'Harirampur', 'bn_name' => 'হরিরামপুর'],
                ['name' => 'Manikganj Sadar', 'bn_name' => 'মানিকগঞ্জ সদর'],
                ['name' => 'Saturia', 'bn_name' => 'সাটুরিয়া'],
                ['name' => 'Shivalaya', 'bn_name' => 'শিবালয়'],
                ['name' => 'Singair', 'bn_name' => 'সিঙ্গাইর'],
            ],
            'Munshiganj' => [
                ['name' => 'Gazaria', 'bn_name' => 'গজারিয়া'],
                ['name' => 'Lohajang', 'bn_name' => 'লৌহজং'],
                ['name' => 'Munshiganj Sadar', 'bn_name' => 'মুন্সীগঞ্জ সদর'],
                ['name' => 'Sirajdikhan', 'bn_name' => 'সিরাজদিখান'],
                ['name' => 'Sreenagar', 'bn_name' => 'শ্রীনগর'],
                ['name' => 'Tongibari', 'bn_name' => 'টঙ্গীবাড়ী'],
            ],
            'Narsingdi' => [
                ['name' => 'Belabo', 'bn_name' => 'বেলাবো'],
                ['name' => 'Monohardi', 'bn_name' => 'মনোহরদী'],
                ['name' => 'Narsingdi Sadar', 'bn_name' => 'নরসিংদী সদর'],
                ['name' => 'Palash', 'bn_name' => 'পলাশ'],
                ['name' => 'Raipura', 'bn_name' => 'রায়পুরা'],
                ['name' => 'Shibpur', 'bn_name' => 'শিবপুর'],
            ],
            'Gopalganj' => [
                ['name' => 'Gopalganj Sadar', 'bn_name' => 'গোপালগঞ্জ সদর'],
                ['name' => 'Kashiani', 'bn_name' => 'কাশিয়ানী'],
                ['name' => 'Kotalipara', 'bn_name' => 'কোটালীপাড়া'],
                ['name' => 'Muksudpur', 'bn_name' => 'মুকসুদপুর'],
                ['name' => 'Tungipara', 'bn_name' => 'টুঙ্গিপাড়া'],
            ],
            'Madaripur' => [
                ['name' => 'Kalkini', 'bn_name' => 'কালকিনি'],
                ['name' => 'Madaripur Sadar', 'bn_name' => 'মাদারীপুর সদর'],
                ['name' => 'Rajoir', 'bn_name' => 'রাজৈর'],
                ['name' => 'Shibchar', 'bn_name' => 'শিবচর'],
                ['name' => 'Dasar', 'bn_name' => 'ডাসার'],
            ],
            'Rajbari' => [
                ['name' => 'Baliakandi', 'bn_name' => 'বালিয়াকান্দি'],
                ['name' => 'Goalandaghat', 'bn_name' => 'গোয়ালন্দঘাট'],
                ['name' => 'Pangsha', 'bn_name' => 'পাংশা'],
                ['name' => 'Rajbari Sadar', 'bn_name' => 'রাজবাড়ী সদর'],
                ['name' => 'Kalukhali', 'bn_name' => 'কালুখালী'],
            ],
            'Shariatpur' => [
                ['name' => 'Bhedarganj', 'bn_name' => 'ভেদরগঞ্জ'],
                ['name' => 'Damudya', 'bn_name' => 'ডামুড্যা'],
                ['name' => 'Gosairhat', 'bn_name' => 'গোসাইরহাট'],
                ['name' => 'Naria', 'bn_name' => 'নড়িয়া'],
                ['name' => 'Shariatpur Sadar', 'bn_name' => 'শরীয়তপুর সদর'],
                ['name' => 'Zajira', 'bn_name' => 'জাজিরা'],
            ],
            'Khagrachhari' => [
                ['name' => 'Dighinala', 'bn_name' => 'দীঘিনালা'],
                ['name' => 'Khagrachhari Sadar', 'bn_name' => 'খাগড়াছড়ি সদর'],
                ['name' => 'Lakshmichhari', 'bn_name' => 'লক্ষীছড়ি'],
                ['name' => 'Mahalchhari', 'bn_name' => 'মহালছড়ি'],
                ['name' => 'Manikchhari', 'bn_name' => 'মানিকছড়ি'],
                ['name' => 'Matiranga', 'bn_name' => 'মাটিরাঙ্গা'],
                ['name' => 'Panchhari', 'bn_name' => 'পানছড়ি'],
                ['name' => 'Ramgarh', 'bn_name' => 'রামগড়'],
                ['name' => 'Guimara', 'bn_name' => 'গুইমারা'],
            ],
            'Rangamati' => [
                ['name' => 'Baghaichhari', 'bn_name' => 'বাঘাইছড়ি'],
                ['name' => 'Barkal', 'bn_name' => 'বরকল'],
                ['name' => 'Kawkhali', 'bn_name' => 'কাউখালী'],
                ['name' => 'Belaichhari', 'bn_name' => 'বিলাইছড়ি'],
                ['name' => 'Kaptai', 'bn_name' => 'কাপ্তাই'],
                ['name' => 'Juraichhari', 'bn_name' => 'জুরাছড়ি'],
                ['name' => 'Langadu', 'bn_name' => 'লংগদু'],
                ['name' => 'Naniarchar', 'bn_name' => 'নানিয়ারচর'],
                ['name' => 'Rajasthali', 'bn_name' => 'রাজস্থলী'],
                ['name' => 'Rangamati Sadar', 'bn_name' => 'রাঙ্গামাটি সদর'],
            ],
            'Bandarban' => [
                ['name' => 'Ali Kadam', 'bn_name' => 'আলীকদম'],
                ['name' => 'Bandarban Sadar', 'bn_name' => 'বান্দরবান সদর'],
                ['name' => 'Lama', 'bn_name' => 'লামা'],
                ['name' => 'Naikhongchhari', 'bn_name' => 'নাইক্ষ্যংছড়ি'],
                ['name' => 'Rowangchhari', 'bn_name' => 'রোয়াংছড়ি'],
                ['name' => 'Ruma', 'bn_name' => 'রুমা'],
                ['name' => 'Thanchi', 'bn_name' => 'থানচি'],
            ],
            'Chapainawabganj' => [
                ['name' => 'Bholahat', 'bn_name' => 'ভোলাহাট'],
                ['name' => 'Chapainawabganj Sadar', 'bn_name' => 'চাঁপাইনবাবগঞ্জ সদর'],
                ['name' => 'Gomastapur', 'bn_name' => 'গোমস্তাপুর'],
                ['name' => 'Nachole', 'bn_name' => 'নাচোল'],
                ['name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ'],
            ],
            'Joypurhat' => [
                ['name' => 'Akkelpur', 'bn_name' => 'আক্কেলপুর'],
                ['name' => 'Joypurhat Sadar', 'bn_name' => 'জয়পুরহাট সদর'],
                ['name' => 'Kalai', 'bn_name' => 'কালাই'],
                ['name' => 'Khetlal', 'bn_name' => 'ক্ষেতলাল'],
                ['name' => 'Panchbibi', 'bn_name' => 'পাঁচবিবি'],
            ],
            'Naogaon' => [
                ['name' => 'Atrai', 'bn_name' => 'আত্রাই'],
                ['name' => 'Badalgachhi', 'bn_name' => 'বদলগাছী'],
                ['name' => 'Dhamoirhat', 'bn_name' => 'ধামইরহাট'],
                ['name' => 'Manda', 'bn_name' => 'মান্দা'],
                ['name' => 'Mohadevpur', 'bn_name' => 'মহাদেবপুর'],
                ['name' => 'Naogaon Sadar', 'bn_name' => 'নওগাঁ সদর'],
                ['name' => 'Niamatpur', 'bn_name' => 'নিয়ামতপুর'],
                ['name' => 'Patnitala', 'bn_name' => 'পত্নীতলা'],
                ['name' => 'Porsha', 'bn_name' => 'পোরশা'],
                ['name' => 'Raninagar', 'bn_name' => 'রানীনগর'],
                ['name' => 'Sapahar', 'bn_name' => 'সাপাহার'],
            ],
            'Natore' => [
                ['name' => 'Bagatipara', 'bn_name' => 'বাগাতিপাড়া'],
                ['name' => 'Baraigram', 'bn_name' => 'বড়াইগ্রাম'],
                ['name' => 'Gurudaspur', 'bn_name' => 'গুরুদাসপুর'],
                ['name' => 'Lalpur', 'bn_name' => 'লালপুর'],
                ['name' => 'Natore Sadar', 'bn_name' => 'নাটোর সদর'],
                ['name' => 'Singra', 'bn_name' => 'সিংড়া'],
                ['name' => 'Naldanga', 'bn_name' => 'নলডাঙ্গা'],
            ],
            'Sirajganj' => [
                ['name' => 'Belkuchi', 'bn_name' => 'বেলকুচি'],
                ['name' => 'Chauhali', 'bn_name' => 'চৌহালি'],
                ['name' => 'Kamarkhanda', 'bn_name' => 'কামারখন্দ'],
                ['name' => 'Kazipur', 'bn_name' => 'কাজীপুর'],
                ['name' => 'Raiganj', 'bn_name' => 'রায়গঞ্জ'],
                ['name' => 'Shahjadpur', 'bn_name' => 'শাহজাদপুর'],
                ['name' => 'Sirajganj Sadar', 'bn_name' => 'সিরাজগঞ্জ সদর'],
                ['name' => 'Tarash', 'bn_name' => 'তাড়াশ'],
                ['name' => 'Ullahpara', 'bn_name' => 'উল্লাপাড়া'],
            ],
            'Bagerhat' => [
                ['name' => 'Bagerhat Sadar', 'bn_name' => 'বাগেরহাট সদর'],
                ['name' => 'Chitalmari', 'bn_name' => 'চিতলমারী'],
                ['name' => 'Fakirhat', 'bn_name' => 'ফকিরহাট'],
                ['name' => 'Kachua', 'bn_name' => 'কচুয়া'],
                ['name' => 'Mollahat', 'bn_name' => 'মোল্লাহাট'],
                ['name' => 'Mongla', 'bn_name' => 'মংলা'],
                ['name' => 'Morrelganj', 'bn_name' => 'মোড়েলগঞ্জ'],
                ['name' => 'Rampal', 'bn_name' => 'রামপাল'],
                ['name' => 'Sarankhola', 'bn_name' => 'শরণখোলা'],
            ],
            'Chuadanga' => [
                ['name' => 'Alamdanga', 'bn_name' => 'আলমডাঙ্গা'],
                ['name' => 'Chuadanga Sadar', 'bn_name' => 'চুয়াডাঙ্গা সদর'],
                ['name' => 'Damurhuda', 'bn_name' => 'দামুড়হুদা'],
                ['name' => 'Jibannagar', 'bn_name' => 'জীবননগর'],
            ],
            'Jhenaidah' => [
                ['name' => 'Harinakunda', 'bn_name' => 'হরিণাকুণ্ডু'],
                ['name' => 'Jhenaidah Sadar', 'bn_name' => 'ঝিনাইদহ সদর'],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
                ['name' => 'Kotchandpur', 'bn_name' => 'কোটচাঁদপুর'],
                ['name' => 'Maheshpur', 'bn_name' => 'মহেশপুর'],
                ['name' => 'Shailkupa', 'bn_name' => 'শৈলকুপা'],
            ],
            'Magura' => [
                ['name' => 'Magura Sadar', 'bn_name' => 'মাগুরা সদর'],
                ['name' => 'Mohammadpur', 'bn_name' => 'মহম্মদপুর'],
                ['name' => 'Shalikha', 'bn_name' => 'শালিখা'],
                ['name' => 'Sreepur', 'bn_name' => 'শ্রীপুর'],
            ],
            'Meherpur' => [
                ['name' => 'Gangni', 'bn_name' => 'গাংনী'],
                ['name' => 'Meherpur Sadar', 'bn_name' => 'মেহেরপুর সদর'],
                ['name' => 'Mujibnagar', 'bn_name' => 'মুজিবনগর'],
            ],
            'Narail' => [
                ['name' => 'Kalia', 'bn_name' => 'কালিয়া'],
                ['name' => 'Lohagara', 'bn_name' => 'লোহাগড়া'],
                ['name' => 'Narail Sadar', 'bn_name' => 'নড়াইল সদর'],
            ],
            'Satkhira' => [
                ['name' => 'Assasuni', 'bn_name' => 'আশাশুনি'],
                ['name' => 'Debhata', 'bn_name' => 'দেবহাটা'],
                ['name' => 'Kalaroa', 'bn_name' => 'কলারোয়া'],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
                ['name' => 'Satkhira Sadar', 'bn_name' => 'সাতক্ষীরা সদর'],
                ['name' => 'Shyamnagar', 'bn_name' => 'শ্যামনগর'],
                ['name' => 'Tala', 'bn_name' => 'তালা'],
            ],
            'Barguna' => [
                ['name' => 'Amtali', 'bn_name' => 'আমতলী'],
                ['name' => 'Bamna', 'bn_name' => 'বামনা'],
                ['name' => 'Barguna Sadar', 'bn_name' => 'বরগুনা সদর'],
                ['name' => 'Betagi', 'bn_name' => 'বেতাগী'],
                ['name' => 'Patharghata', 'bn_name' => 'পাথরঘাটা'],
                ['name' => 'Taltali', 'bn_name' => 'তালতলী'],
            ],
            'Bhola' => [
                ['name' => 'Bhola Sadar', 'bn_name' => 'ভোলা সদর'],
                ['name' => 'Burhanuddin', 'bn_name' => 'বোরহানউদ্দিন'],
                ['name' => 'Char Fasson', 'bn_name' => 'চরফ্যাশন'],
                ['name' => 'Daulatkhan', 'bn_name' => 'দৌলতখান'],
                ['name' => 'Lalmohan', 'bn_name' => 'লালমোহন'],
                ['name' => 'Manpura', 'bn_name' => 'মনপুরা'],
                ['name' => 'Tazumuddin', 'bn_name' => 'তজুমদ্দিন'],
            ],
            'Jhalokati' => [
                ['name' => 'Jhalokati Sadar', 'bn_name' => 'ঝালকাঠি সদর'],
                ['name' => 'Kathalia', 'bn_name' => 'কাঁঠালিয়া'],
                ['name' => 'Nalchity', 'bn_name' => 'নলছিটি'],
                ['name' => 'Rajapur', 'bn_name' => 'রাজাপুর'],
            ],
            'Patuakhali' => [
                ['name' => 'Bauphal', 'bn_name' => 'বাউফল'],
                ['name' => 'Dashmina', 'bn_name' => 'দশমিনা'],
                ['name' => 'Galachipa', 'bn_name' => 'গলাচিপা'],
                ['name' => 'Kalapara', 'bn_name' => 'কলাপাড়া'],
                ['name' => 'Mirzaganj', 'bn_name' => 'মির্জাগঞ্জ'],
                ['name' => 'Patuakhali Sadar', 'bn_name' => 'পটুয়াখালী সদর'],
                ['name' => 'Rangabali', 'bn_name' => 'রাঙ্গাবালী'],
                ['name' => 'Dumki', 'bn_name' => 'দুমকি'],
            ],
            'Pirojpur' => [
                ['name' => 'Bhandaria', 'bn_name' => 'ভান্ডারিয়া'],
                ['name' => 'Kawkhali', 'bn_name' => 'কাউখালী'],
                ['name' => 'Mathbaria', 'bn_name' => 'মঠবাড়িয়া'],
                ['name' => 'Nazirpur', 'bn_name' => 'নাজিরপুর'],
                ['name' => 'Pirojpur Sadar', 'bn_name' => 'পিরোজপুর সদর'],
                ['name' => 'Nesarabad', 'bn_name' => 'নেছারাবাদ'],
                ['name' => 'Indurkani', 'bn_name' => 'ইন্দুরকানী'],
            ],
            'Habiganj' => [
                ['name' => 'Ajmiriganj', 'bn_name' => 'আজমিরীগঞ্জ'],
                ['name' => 'Bahubal', 'bn_name' => 'বাহুবল'],
                ['name' => 'Baniachong', 'bn_name' => 'বানিিয়াচং'],
                ['name' => 'Chunarughat', 'bn_name' => 'চুনারুঘাট'],
                ['name' => 'Habiganj Sadar', 'bn_name' => 'হবিগঞ্জ সদর'],
                ['name' => 'Lakhai', 'bn_name' => 'লাখাই'],
                ['name' => 'Madhabpur', 'bn_name' => 'মাধবপুর'],
                ['name' => 'Nabiganj', 'bn_name' => 'নবীগঞ্জ'],
                ['name' => 'Shayestaganj', 'bn_name' => 'শায়েস্তাগঞ্জ'],
            ],
            'Moulvibazar' => [
                ['name' => 'Barlekha', 'bn_name' => 'বড়লেখা'],
                ['name' => 'Juri', 'bn_name' => 'জুড়ী'],
                ['name' => 'Kamalganj', 'bn_name' => 'কমলগঞ্জ'],
                ['name' => 'Kulaura', 'bn_name' => 'কুলাউড়া'],
                ['name' => 'Moulvibazar Sadar', 'bn_name' => 'মৌলভীবাজার সদর'],
                ['name' => 'Rajnagar', 'bn_name' => 'রাজনগর'],
                ['name' => 'Sreemangal', 'bn_name' => 'শ্রীমঙ্গল'],
            ],
            'Sunamganj' => [
                ['name' => 'Bishwamvarpur', 'bn_name' => 'বিশ্বম্ভরপুর'],
                ['name' => 'Chhatak', 'bn_name' => 'ছাতক'],
                ['name' => 'Dakshin Sunamganj', 'bn_name' => 'দক্ষিণ সুনামগঞ্জ'],
                ['name' => 'Derai', 'bn_name' => 'দিরাই'],
                ['name' => 'Dharmapasha', 'bn_name' => 'ধর্মপাশা'],
                ['name' => 'Dowarabazar', 'bn_name' => 'দোয়ারাবাজার'],
                ['name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর'],
                ['name' => 'Jamalganj', 'bn_name' => 'জামালগঞ্জ'],
                ['name' => 'Sullah', 'bn_name' => 'শাল্লা'],
                ['name' => 'Sunamganj Sadar', 'bn_name' => 'সুনামগঞ্জ সদর'],
                ['name' => 'Tahirpur', 'bn_name' => 'তাহিরপুর'],
            ],
            'Gaibandha' => [
                ['name' => 'Fulchhari', 'bn_name' => 'ফুলছড়ি'],
                ['name' => 'Gaibandha Sadar', 'bn_name' => 'গাইবান্ধা সদর'],
                ['name' => 'Gobindaganj', 'bn_name' => 'গোবিন্দগঞ্জ'],
                ['name' => 'Palashbari', 'bn_name' => 'পলাশবাড়ী'],
                ['name' => 'Sadullapur', 'bn_name' => 'সাদুল্লাপুর'],
                ['name' => 'Saghata', 'bn_name' => 'সাঘাটা'],
                ['name' => 'Sundarganj', 'bn_name' => 'সুন্দরগঞ্জ'],
            ],
            'Kurigram' => [
                ['name' => 'Bhurungamari', 'bn_name' => 'ভুরুঙ্গামারী'],
                ['name' => 'Char Rajibpur', 'bn_name' => 'চর রাজিবপুর'],
                ['name' => 'Chilmari', 'bn_name' => 'চিলমারী'],
                ['name' => 'Kurigram Sadar', 'bn_name' => 'কুড়িগ্রাম সদর'],
                ['name' => 'Nageshwari', 'bn_name' => 'নাগেশ্বরী'],
                ['name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ী'],
                ['name' => 'Rajarhat', 'bn_name' => 'রাজারহাট'],
                ['name' => 'Raumari', 'bn_name' => 'রৌমারী'],
                ['name' => 'Ulipur', 'bn_name' => 'উলিপুর'],
            ],
            'Lalmonirhat' => [
                ['name' => 'Aditmari', 'bn_name' => 'আদিতমারী'],
                ['name' => 'Hatibandha', 'bn_name' => 'হাতীবান্ধা'],
                ['name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ'],
                ['name' => 'Lalmonirhat Sadar', 'bn_name' => 'লালমনিরহাট সদর'],
                ['name' => 'Patgram', 'bn_name' => 'পাটগ্রাম'],
            ],
            'Nilphamari' => [
                ['name' => 'Dimla', 'bn_name' => 'ডিমলা'],
                ['name' => 'Domar', 'bn_name' => 'ডোমার'],
                ['name' => 'Jaldhaka', 'bn_name' => 'জলঢাকা'],
                ['name' => 'Kishoreganj', 'bn_name' => 'কিশোরগঞ্জ'],
                ['name' => 'Nilphamari Sadar', 'bn_name' => 'নীলফামারী সদর'],
                ['name' => 'Saidpur', 'bn_name' => 'সৈয়দপুর'],
            ],
            'Panchagarh' => [
                ['name' => 'Atwari', 'bn_name' => 'আটোয়ারী'],
                ['name' => 'Boda', 'bn_name' => 'বোদা'],
                ['name' => 'Debiganj', 'bn_name' => 'দেবীগঞ্জ'],
                ['name' => 'Panchagarh Sadar', 'bn_name' => 'পঞ্চগড় সদর'],
                ['name' => 'Tetulia', 'bn_name' => 'তেঁতুলিয়া'],
            ],
            'Thakurgaon' => [
                ['name' => 'Baliadangi', 'bn_name' => 'বালিয়াডাঙ্গী'],
                ['name' => 'Haripur', 'bn_name' => 'হরিপুর'],
                ['name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ'],
                ['name' => 'Ranisankail', 'bn_name' => 'রাণীশংকৈল'],
                ['name' => 'Thakurgaon Sadar', 'bn_name' => 'ঠাকুরগাঁও সদর'],
            ],
            'Netrokona' => [
                ['name' => 'Atpara', 'bn_name' => 'আটপাড়া'],
                ['name' => 'Barhatta', 'bn_name' => 'বারহাট্টা'],
                ['name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর'],
                ['name' => 'Khaliajuri', 'bn_name' => 'খালিয়াজুড়ী'],
                ['name' => 'Kalmakanda', 'bn_name' => 'কলমাকান্দা'],
                ['name' => 'Kendua', 'bn_name' => 'কেন্দুয়া'],
                ['name' => 'Madan', 'bn_name' => 'মদন'],
                ['name' => 'Mohanganj', 'bn_name' => 'মোহনগঞ্জ'],
                ['name' => 'Netrokona Sadar', 'bn_name' => 'নেত্রকোণা সদর'],
                ['name' => 'Purbadhala', 'bn_name' => 'পূর্বধলা'],
            ],
            'Sherpur' => [
                ['name' => 'Jhenaigati', 'bn_name' => 'ঝিনাইগাতী'],
                ['name' => 'Nakla', 'bn_name' => 'নাকলা'],
                ['name' => 'Nalitabari', 'bn_name' => 'নালিতাবাড়ী'],
                ['name' => 'Sherpur Sadar', 'bn_name' => 'শেরপুর সদর'],
                ['name' => 'Sreebardi', 'bn_name' => 'শ্রীবরদী'],
            ],
        ];

        $allThanas = array_merge($districtsThanas, $moreDistricts);

        foreach ($allThanas as $districtName => $thanas) {
            $district = District::where('name', $districtName)->first();

            if ($district) {
                foreach ($thanas as $thanaData) {
                    $defaultData = [
                        'bn_name' => $thanaData['bn_name'],
                    ];

                    $district->thanas()->updateOrCreate(
                        ['name' => $thanaData['name']],
                        $defaultData
                    );
                }
            }
        }
    }
}
